spring:
  application:
    name: body-track

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        show_sql: false

  datasource:
    username: ${SYNC-LIFE_DATABASE_USERNAME}
    password: ${SYNC-LIFE_DATABASE_PASSWORD}
    url: jdbc:mysql://${SYNC-LIFE_DATABASE_HOSTNAME}:${SYNC-LIFE_DATABASE_PORT}/${SYNC-LIFE_DATABASE_NAME}?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo

  rabbitmq:
    host: ${SYNC-LIFE_RABBITMQ_HOSTNAME}
    port: ${SYNC-LIFE_RABBITMQ_PORT}
    username: ${SYNC-LIFE_RABBITMQ_USERNAME}
    password: ${SYNC-LIFE_RABBITMQ_PASSWORD}
    ssl:
      enabled: false

sync-life:
  health:
    body-track:
      queue: body-track
  rabbitmq:
    exchange: ${SYNC-LIFE_RABBITMQ_EXCHANGE}
